### ISSUE TITLE
Infinite loader after creating character and trying to save

### ISSUE THREAD

**Issue by Ihellmasker** [BDO-Planner/issues#230]
In GitLab by @nerfworthy on Mar 10, 2021, 16:08

**Description**  
When making a new character, trying to save it causes an infinite loading screen and character is lost in the process. 

**Steps to Reproduce**  

1. Login to account
2. Create new character (in this case it was Lahn)
3. Add all gear (TET boss armor, TET weapons and TET accessories)
4. Click save button
5. Observe infinite loading screen

**Expected Behavior**  
Character would save and be accessible from profile

**Actual Behavior**  
Character is lost when trying to save due to infinite loading screen

**Comment by SalvationsLight** [comment]
Hello! I'm having this same issue, every time I try to save a build. Here is a copy and past of the error that shows in the console in Firefox.

Uncaught (in promise) TypeError: i.save is undefined in bdo-planner-app-00f5a0a40496015902335594c2ab14e7.js:1304:18
    e https://bdoplanner.com/assets/bdo-planner-app-00f5a0a40496015902335594c2ab14e7.js:1304
    c https://bdoplanner.com/assets/vendor-5d325c95bc3f8d94b08d7f40c9c6a14d.js:74
    _invoke https://bdoplanner.com/assets/vendor-5d325c95bc3f8d94b08d7f40c9c6a14d.js:71
    t https://bdoplanner.com/assets/vendor-5d325c95bc3f8d94b08d7f40c9c6a14d.js:74
    _resumeGenerator https://bdoplanner.com/assets/vendor-5d325c95bc3f8d94b08d7f40c9c6a14d.js:9570
    _handleResolvedContinueValue https://bdoplanner.com/assets/vendor-5d325c95bc3f8d94b08d7f40c9c6a14d.js:9580
    _proceed https://bdoplanner.com/assets/vendor-5d325c95bc3f8d94b08d7f40c9c6a14d.js:9573
    invoke https://bdoplanner.com/assets/vendor-5d325c95bc3f8d94b08d7f40c9c6a14d.js:4235
    flush https://bdoplanner.com/assets/vendor-5d325c95bc3f8d94b08d7f40c9c6a14d.js:4227
    flush https://bdoplanner.com/assets/vendor-5d325c95bc3f8d94b08d7f40c9c6a14d.js:4241
    _end https://bdoplanner.com/assets/vendor-5d325c95bc3f8d94b08d7f40c9c6a14d.js:4304
    _boundAutorunEnd https://bdoplanner.com/assets/vendor-5d325c95bc3f8d94b08d7f40c9c6a14d.js:4255


There is also a warning:

Cookie “csrf” has been rejected because it is already expired.     login-callback

**Comment by Ihellmasker** [comment]
Are you able to give steps to replicate the issue? @SalvationsLight

**Comment by SalvationsLight** [comment]
I followed the same steps as the first poster. Thanks :)

**Comment by nebman227** [comment]
I just had a similar issue, but with editing an existing character rather than making a new. I figured that it was similar enough that I shouldn't open a new issue. I created 2 new builds for an existing character, but when I pressed "save" I was sent to a loading screen. So far, I clicked save 50 minutes ago and the loading screen is still shown. I opened a new tab and tried to access planner again, but that tab is still loading as well. About ten minutes after the initial attempt to save, I opened a third tab with bdoplanner on it and successfully accessed the character, but without any of the changes that I made saved.

**Comment by DotChris** [comment]
I only get the error if I try to save to an existing build after having the tab open for some time(hours? days? not sure). Also on Firefox. Refreshing the url always seems to resolve this issue.

**Comment by Ihellmasker** [comment]
I'm working on a lot of rewrites in 3.0 so hopefully this issue gets fixed with it. I'm struggling to replicate this on the current and new version.

> I only get the error if I try to save to an existing build after having the tab open for some time(hours? days? not sure). Also on Firefox. Refreshing the url always seems to resolve this issue.

This is most likely the session expiring. Not sure if everyone else is having the game issue. That one I can't help with, although I'm adding something in that may stop that being quite as annoying #88

**Comment by Ihellmasker** [comment]
I'm going to make this as closed for now. 3.0 is currently in testing at https://staging.bdoplanner.com/ and you're welcome to try it and see it if now works for you. I believe this issue is resolved but as I could never replicate it, it's hard to tell.

If you think it's still an issue, then feel free to reply and we can reopen it.
