### ISSUE TITLE
Build page stay in loading forever

### ISSUE THREAD

**Issue by pinghsien422** [BDO-Planner/issues#278]
### Prerequisites

- [X] I have [searched](https://github.com/BDO-Planner/issues/issues) for duplicate or closed issues.
- [X] I have read the [Common Issues](https://github.com/BDO-Planner/issues/blob/master/README.md).

### Describe the bug

One of my character build page does not load, stays in load screen forever.
Other characters are fine.

The profile with issue is:
https://bdoplanner.com/SubjectTashuSnow

### How did the bug happen

1. Type in https://bdoplanner.com/SubjectTashuSnow
2. Page stays in loading forever.
3. Try go to my other build page by typing https://bdoplanner.com/RatDirtGrunil
4. Page loads correctly.

### Expected behavior

The build page should load correctly.

**Comment by rexizam** [comment]
Same here. Link to profile: https://bdoplanner.com/TerminateSorDrieghan

**Comment by SsanSsan** [comment]
Same here too. Since 1-2 days ago and it's this profile: https://bdoplanner.com/TaddShoesSandstorm

**Comment by Ihellmasker** [comment]
Okay so, some good news and bad news.

The issue happened due to the new skill reworks that we tried dropped a few days ago, didn't realise at the that it'd break builds due to the complete difference in skill ids and skill levels.

So, good news is, we've fixed the issue now...

Bad news is, that involved us removing all skills from all builds, so unfortunately you'll need to reset the skills on your builds.

Sorry about that :(.
